# Site settings
title: Machine Epistemology
author: Roban Hultman Kramer
description: > # this means to ignore newlines until "baseurl:"
 Machine Learning, Inference, Prediction, Epistemology, Philosophy of
 Science, Freediving, and Rainbows.

twitter_username: robanhk
github_username: roban
email: robanhk
homepage: http://roban.github.io/

baseurl: /machine-epistemology

# Build settings
markdown: kramdown
highlighter: pygments

safe: true
