# Site settings
title: Machine Epistemology
author: Roban Hultman Kramer
description: > # this means to ignore newlines until "baseurl:"
 Responsible Machine Learning, Epistemology
baseurl: /machine-epistemology

twitter_username: robanhk
github_username: roban
email: robanhk
homepage: http://roban.github.io/

# Build settings
safe: true
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge