# Site settings
title: Machine Epistemology
author: Roban Hultman Kramer
description: Responsible Machine Learning, Epistemology
baseurl: /machine-epistemology

twitter_username: robanhk
mastodon_instance: sigmoid.social
mastodon_username: roban
github_username: roban
email: robanhk@gmail.com
homepage: http://roban.github.io/

# Build settings
safe: true
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge