# Site settings
title: Machine Epistemology
author: Roban Hultman Kramer
description: > # this means to ignore newlines until "baseurl:"
 Machine Learning, Inference, Prediction, Fairness in Machine Learning, Epistemology,
 Philosophy of Science, Freediving, and Rainbows.
baseurl: /machine-epistemology

twitter_username: robanhk
github_username: roban
email: robanhk
homepage: http://roban.github.io/

# Build settings
markdown: kramdown
highlighter: rouge

safe: true
